### PR TITLE
feat: add GeoM for Drawing Shifts and Deprecated Camera

### PR DESCRIPTION
**Pull request by demouth**
## Summary

- Added GeoM for shifting drawings.
- Since GeoM can now handle camera functionality, the Camera type is deprecated.
- Implements the proposal from issue #2.

### CODE REVIEW

**Comment by setanarut** [comment]
Nice, I also completely disabled the bottom-left coordinate system option. I upgraded Theo Jansen code according to the Ebitengine coordinate system. 

```
go run github.com/setanarut/ebitencm/examples/theojansen_cam@latest
```

I added `Theme` struct to customize colors. https://github.com/setanarut/ebitencm/blob/main/ebitencm.go#L275

**Comment by setanarut** [comment]
You can make public all `DrawTrianglesOptions` and other settings.

**Comment by demouth** [comment]
I understand the request to disable the coordinate system change option, but I have some mixed feelings since my original goal was to ensure compatibility with [jakecoffman/cp-examples](https://github.com/jakecoffman/cp-examples).

Also, the Theme feature looks great—I'll definitely use it as a reference.

**Comment by demouth** [comment]
You’re right, it does seem better for `DrawTrianglesOptions` to be public. I’ll go ahead and change it to public.

**Comment by setanarut** [comment]
> I understand the request to disable the coordinate system change option, but I have some mixed feelings since my original goal was to ensure compatibility with [jakecoffman/cp-examples](https://github.com/jakecoffman/cp-examples).
> 
> Also, the Theme feature looks great—I'll definitely use it as a reference.

I understand you, it's up to you. My main goal is to ensure compatibility with Ebitengine.

**Comment by demouth** [comment]
I’ve made DrawTrianglesOptions public and marked AntiAlias as deprecated.

I’ll address the Theme feature separately.

**Pull request merged**
